services:
  postgres:
    container_name: url-shortener-postgres
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default
    ports:
      - "5432:5432"
    restart: always